export const CART = {
  GET_CART: 'GET_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART'
};

export const WISHLIST = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};

export const SHOP = {
  SET_FILTER_CATEGORY: "SET_FILTER_CATEGORY",
  SET_FILTER_PRICE_RANGE: "SET_FILTER_PRICE_RANGE",
  SET_FILTER_BRAND: "SET_FILTER_BRAND",
  RESET_FILTER: "RESET_FILTER",
};

export const HomePage1 ={
  SET_FILTER_PRODUCT_HOMEPAGE1: "SET_FILTER_PRODUCT_HOMEPAGE1",
  
}

export const Product = {
  SET_FILTER_PRODUCT: "SET_FILTER_PRODUCT",
  SET_FILTER_PRODUCT_DETAIL: "SET_FILTER_PRODUCT_DETAIL",
  GET_ALL_PRODUCT_BY_FILTER: "GET_ALL_PRODUCT_BY_FILTER",
  
}

export const User = {
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
}

export const Order = {
  GET_ALL_ORDER: "GET_ALL_ORDER",
  GET_ORDER_DETAIL: "GET_ORDER_DETAIL",
  CREATE_ORDER: "CREATE_ORDER",
}

export const Address = {
  GET_ALL_ADDRESS: "GET_ALL_ADDRESS",
  GET_ADDRESS_DETAIL: "GET_ADDRESS_DETAIL",
  CREATE_ADDRESS: "CREATE_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
}


